new update pipeline5

diff --git a/.github/workflows/cd.yaml b/.github/workflows/cd.yaml
--- a/.github/workflows/cd.yaml
+++ b/.github/workflows/cd.yaml
@@ -65,10 +65,10 @@ jobs:
         run: |
           trivy image --exit-code 1 --severity HIGH,CRITICAL $username/$image_name:$version || true
 
-      - name: Run Tests
-        run: |
-          echo "Running smoke tests..."
-          npm run test:smoke || { echo 'Smoke tests failed'; exit 1; }
+      -  name: Run Tests
+         run: |
+            echo "Running tests..."
+            npm test || { echo 'Tests failed'; exit 1; }
 
 
   Deploy:
